dump_path: './'
jit_compile: True
compile_option: -O3
compare_algorithm: cosine_similarity
real_data: False
dump_step: 1000
error_data_path: './'
enable_dataloader: True
target_iter: 1
precision: 14
 